apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        env:
        - name: CUST_NGINX_PORT
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: CUST_NGINX_PORT
        - name: CUST_NGINX_WORKER_PROCESSES
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: CUST_NGINX_WORKER_PROCESSES