apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: rolling
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: nginx-config