apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-basic
  namespace: rolling
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
