apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-basic
  namespace: rolling
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
