apiVersion: v1
kind: Service
metadata:
  name: nginx-service-with-pvc
  namespace: rolling
  labels:
    app: nginx-with-pvc
spec:
  selector:
    app: nginx-with-pvc
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP