# Default values for nginx-app
replicaCount: 2

image:
  repository: nginx
  tag: 1.19.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

configMap:
  nginxPort: "8080"
  nginxWorkerProcesses: "2"

namespace: rolling